### ISSUE TITLE
Min and max, maxlength

### ISSUE THREAD

**Issue by codeorlov** [RensTillmann/super-forms#23] opened 2020-04-10 05:41 UTC
1. Hello, is it possible to restrict the user in entering negative numeric characters in a text field? Or how is it implemented here? You must prevent the user from choosing numbers less than 0.
in html this is done like this:
`<input type = "number" min = "minimum number">`

2. How to limit the number of characters to enter? In html:
`<input type = "text" maxlength = "number">`

**Comment by RensTillmann** [comment] 2020-04-10 17:01
Hi for text field you can set "max/min characters" under "Advanced" settings to limit the amount of characters that can be entered. Please note that it will validate after the field is "blurred" or the form is submitted.

For a text field with type "number" I think there might be a bug with the "min number" setting when it's set to "0" I can't get it to work. Any other value works fine.

Will make sure to solve it in the next version.

**Comment by codeorlov** [comment] 2020-04-15 15:59
"Please note that it will validate after the field is "blurred" or the form is submitted."

I would like to prohibit entering negative numbers in principle, as this breaks the logic of the field dynamics and gives out negative amounts, as well as interferes with customers. How to fix this?

https://prnt.sc/rzxwzh

**Comment by RensTillmann** [comment] 2020-04-15 17:09
I understand what you mean, in that case you would need to set field type to `number`. But the problem is that super forms isn't adding the min/max attribute on the element based of the max/min settings. This will be patched in the next version. When released, you can use it as intended like you initially explained. Thanks.

**Comment by codeorlov** [comment] 2020-04-15 17:50
Thank you, I really expect this fix, the support is great!

**Comment by RensTillmann** [comment] 2020-05-14 00:56
Fixed in v4.9.450

**Closed** 2020-05-14 00:56 UTC
