### ISSUE TITLE
Unique Code Generation happening on the client side

### ISSUE THREAD

**Issue by saeedkola** [RensTillmann/super-forms#28] opened 2020-05-16 10:58 UTC
Unique code generation is happening on the client side, not server side upon form submission.
As a result there are duplicates being created, if the user is submitting multiple form entries.
In my case I have used redirect on submit option to display a custom confirmation message, when the user clicks back button browser to submit another entry, the unique code in the hidden field is not changing and duplicates are being created.

**Comment by RensTillmann** [comment] 2020-05-16 11:46
Thanks for the info, however code generation is not done client side (of course not, that would be rather stupid). But regarding the "Return/Back" button from the browser it might indeed be that the browser is "populating" that specific field with the same "unique" code that was generated beforehand.

We will investigate this issue and try to apply a fix for this scenario. Thanks.

**Comment by RensTillmann** [comment] 2020-05-16 11:50
Hi, could you please attach the form export here for testing purposes? We just tested the issue on our end but it's not happening for us. Also let us know in which browser you done your test.

**Comment by saeedkola** [comment] 2020-05-18 15:20
[super-form-export.zip](https://github.com/RensTillmann/super-forms/files/4644959/super-form-export.zip)
Initially even I thought it was happening because of browser autocomplete. But then I set autocomplete="off" in includes/class-shortcodes.php
`$result .= '<form autocomplete="off" enctype="multipart/form-data"';`
That stopped the form elements from auto populating but the value in the hidden field was still showing the previously generated random code.

**Comment by saeedkola** [comment] 2020-05-18 15:29
![image](https://user-images.githubusercontent.com/5690961/82230959-12c8ca80-994a-11ea-83d6-243838145da9.png)
In the screenshot above you can see that uniqueid2 field value has been set even before submitting the form. In an ideal scenario, IMO, this code should be generated after the form has been submitted.

**Comment by RensTillmann** [comment] 2020-05-20 13:18
Done some more testing on this issue, and was able to reproduce it in Firefox since you are also using that browser. We will make sure to implement a fix for this. The reason that the code is generated before the form is submitted is because this way you can already do things in the form with that generated code. It has it's use cases. Anyway we will make sure that the code will "regenerate" when the "Back" button in the browser was clicked. That way this duplicate issue shouldn't be happening again.

**Comment by RensTillmann** [comment] 2020-05-20 15:08
This issue is now solved in v4.9.454. You can update to that version to solve this problem.

**Closed by RensTillmann** 2020-05-20 15:08 UTC
